name: deploy backend
on:
  workflow_run:
    workflows: ["deploy service"]
    branches: ["main"]
    types:
      - completed
env:
  DOTNET_VERSION: "5.0.x"
  AZURE_WEBAPP_NAME: hackAppBackend-eastus-A01
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: dotnet build on ${{env.DOTNET_VERSION}}
        run: |
          cd src/backend/api/
          dotnet restore
          dotnet build -- configuration Release

      - name: dotnet publish
        run: |

          dotnet publish src/backend/api/api.csproj -c Release -o ./hack_backend_api

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-api
          path: ./hack_backend_api
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-api

      - name: deploy to azure web app
        id: deploy-to-web-app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          package: ./backend-api
